---
- hosts: web_servers
  become: yes
  tasks:
    - name: Install yum-plugin-copr
      dnf:
        name: yum-plugin-copr
        state: present

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Git
      dnf:
        name: git
        state: present

    - name: Ensure Python  is installed
      dnf:
        name: python
        state: present

    - name: Download get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip
      command: python /tmp/get-pip.py --user

    - name: Clone the Python Flask application repository
      git:
        repo: https://github.com/hectorlopezv/python-flash-application
        dest: /home/ec2-user/python-flash-application

    - name: Create a Python virtual environment
      command: python -m venv /home/ec2-user/python-flash-application/venv

    - name: Activate the virtual environment and install requirements
      shell: |
        source /home/ec2-user/python-flash-application/venv/bin/activate
        pip install -r /home/ec2-user/python-flash-application/requirements.txt
        pip install "flask<3" "werkzeug<3"
      args:
        executable: /bin/bash

    - name: Run Flask application in the background
      shell: |
        source /home/ec2-user/python-flash-application/venv/bin/activate
        python -m flask run --host=0.0.0.0 --port=5000
      args:
        executable: /bin/bash

    - name: Enable Caddy repository
      command: dnf -y copr enable @caddy/caddy epel-7-x86_64
      ignore_errors: yes

    - name: Install Caddy
      dnf:
        name: caddy
        state: present


    - name: Replace Caddyfile with the desired configuration
      copy:
        content: |
          :80 {
              reverse_proxy localhost:5000
          }
        dest: /etc/caddy/Caddyfile
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Ensure Caddy service is started and enabled
      service:
        name: caddy
        state: started
        enabled: yes
